### ISSUE TITLE
Spectator issues.

### ISSUE THREAD

**Issue by breezboii** [chanz/redie#2]
When you die and go redie, and then go to spectator, and then move back to the team while being dead - on roundstart you will then get slayed again and be dead for 1 round.

I use a !spec plugin, that when you type !spec, you will be moved to spectator list.

**Comment by chanz** [comment]
Tested in 2.12 and should be fixed. Please test it with version 2.12 and let me know if it was fixed for you too.

Also please attach a link to the plugin.

Version 2.12 will be released today.

**Comment by chanz** [comment]
I assume this is fixed. If not just reopen this issue or a new one.
