### ISSUE TITLE
Plugin still spamming messages

### ISSUE THREAD

**Issue by breezboii** [chanz/redie#7]
Hello, i'm not sure exactly when the plugin are telling people, but i can assure you it spams alot. It's just one message it keeps spamming, so i went into the sp file and removed it, which helped me alot.

But again, still spamming.

**Comment by chanz** [comment]
Hi thanks for the notice and sorry for the late response.

As a walkaround you could also set the cvar to something very high instead of 0.
I'll be sure to fix this in the next version.

**Comment by chanz** [comment]
Timed advertations have been removed in 2.12.
